<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./src/lib/models/Character/egertviieanimatsiooniga.glb -o chargltf -k -s -w -d -u -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('/egertviieanimatsiooniga-transformed.glb', { useDraco: true }))
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="sitting" position={[0, 0, 4.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="Wolf3D_Body004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Wolf3D_Body004.geometry}
          material={gltf.materials['Wolf3D_Body.008']}
          skeleton={gltf.nodes.Wolf3D_Body004.skeleton}
        />
        <T.SkinnedMesh
          name="Wolf3D_Glasses004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Wolf3D_Glasses004.geometry}
          material={gltf.materials['Wolf3D_Glasses.008']}
          skeleton={gltf.nodes.Wolf3D_Glasses004.skeleton}
        />
        <T.SkinnedMesh
          name="Wolf3D_Hair004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Wolf3D_Hair004.geometry}
          material={gltf.materials['Wolf3D_Hair.008']}
          skeleton={gltf.nodes.Wolf3D_Hair004.skeleton}
        />
        <T.SkinnedMesh
          name="Wolf3D_Outfit_Bottom004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Wolf3D_Outfit_Bottom004.geometry}
          material={gltf.materials['Wolf3D_Outfit_Bottom.008']}
          skeleton={gltf.nodes.Wolf3D_Outfit_Bottom004.skeleton}
        />
        <T.SkinnedMesh
          name="Wolf3D_Outfit_Footwear004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Wolf3D_Outfit_Footwear004.geometry}
          material={gltf.materials['Wolf3D_Outfit_Footwear.008']}
          skeleton={gltf.nodes.Wolf3D_Outfit_Footwear004.skeleton}
        />
        <T.SkinnedMesh
          name="Wolf3D_Outfit_Top004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Wolf3D_Outfit_Top004.geometry}
          material={gltf.materials['Wolf3D_Outfit_Top.008']}
          skeleton={gltf.nodes.Wolf3D_Outfit_Top004.skeleton}
        />
        <T.SkinnedMesh
          name="EyeLeft004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.EyeLeft004.geometry}
          material={gltf.materials['Wolf3D_Eye.008']}
          skeleton={gltf.nodes.EyeLeft004.skeleton}
          morphTargetDictionary={gltf.nodes.EyeLeft004.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.EyeLeft004.morphTargetInfluences}
        />
        <T.SkinnedMesh
          name="EyeRight004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.EyeRight004.geometry}
          material={gltf.materials['Wolf3D_Eye.008']}
          skeleton={gltf.nodes.EyeRight004.skeleton}
          morphTargetDictionary={gltf.nodes.EyeRight004.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.EyeRight004.morphTargetInfluences}
        />
        <T.SkinnedMesh
          name="Wolf3D_Head004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Wolf3D_Head004.geometry}
          material={gltf.materials['Wolf3D_Skin.008']}
          skeleton={gltf.nodes.Wolf3D_Head004.skeleton}
          morphTargetDictionary={gltf.nodes.Wolf3D_Head004.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.Wolf3D_Head004.morphTargetInfluences}
        />
        <T.SkinnedMesh
          name="Wolf3D_Teeth004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Wolf3D_Teeth004.geometry}
          material={gltf.materials['Wolf3D_Teeth.008']}
          skeleton={gltf.nodes.Wolf3D_Teeth004.skeleton}
          morphTargetDictionary={gltf.nodes.Wolf3D_Teeth004.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.Wolf3D_Teeth004.morphTargetInfluences}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
