<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./src/lib/models/Campsite/camping_buscraft_ambience.glb -i -T
Author: Edgar_koh (https://sketchfab.com/edgar_koh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/camping-buscraft-ambience-7b65e4df95c3492fbf4e0641e3b472c1
Title: camping buscraft ambience
-->

<script lang="ts">
	import { Group } from 'three';
	import { T } from '@threlte/core';
	import { useGltf, useGltfAnimations, GLTF } from '@threlte/extras';
	import campsite from '$lib/models/Campsite/camping_buscraft_ambience.glb';
	import { degToRad } from 'three/src/math/MathUtils';

	export const ref = new Group();

	const gltf = useGltf(campsite, {
		useDraco: true
	});

	export const { actions } = useGltfAnimations(gltf, ref);

	$: if ($actions) {
		$actions['Take 001']?.play();
	}
</script>

<!-- <GLTF
	receiveShadow
	castShadow
	useDraco
	url={campsite}
	rotation.y={degToRad(0)}
	position={[-0.04, -0.05, -4.27]}
	scale={1}
/> -->

<T is={ref} rotation.y={degToRad(325)} position={[0, 0, -8]} scale={0.9}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Sketchfab_Scene">
			<T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
				<T.Group name="f57d262c2aa44061846a12a5a8f3c5ddfbx" rotation={[Math.PI / 2, 0, 0]}>
					<T.Group name="Object_2">
						<T.Group name="RootNode">
							<T.Group
								name="pPlane184"
								position={[1.61, -0.16, 1.72]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane184_lambert6_0"
									geometry={gltf.nodes.pPlane184_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane185"
								position={[-1.98, 0.08, 3.85]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane185_lambert6_0"
									geometry={gltf.nodes.pPlane185_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane186"
								position={[0.39, 3.92, 1.45]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane186_lambert6_0"
									geometry={gltf.nodes.pPlane186_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane187"
								position={[-2.96, -0.99, 2.44]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane187_lambert6_0"
									geometry={gltf.nodes.pPlane187_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane188"
								position={[1.91, 8.05, -2.18]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane188_lambert6_0"
									geometry={gltf.nodes.pPlane188_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane189"
								position={[0.28, 7.1, 0.96]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane189_lambert6_0"
									geometry={gltf.nodes.pPlane189_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane190"
								position={[-1, 0.21, 2.13]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane190_lambert6_0"
									geometry={gltf.nodes.pPlane190_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane191"
								position={[-2.85, 4.31, 1.9]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane191_lambert6_0"
									geometry={gltf.nodes.pPlane191_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane192"
								position={[2.03, 6.45, -1.81]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane192_lambert6_0"
									geometry={gltf.nodes.pPlane192_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane193"
								position={[-1.57, 2.2, 1.27]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane193_lambert6_0"
									geometry={gltf.nodes.pPlane193_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane194"
								position={[2.82, 4.47, 0.15]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane194_lambert6_0"
									geometry={gltf.nodes.pPlane194_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane195"
								position={[0.05, 0.52, 2.34]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane195_lambert6_0"
									geometry={gltf.nodes.pPlane195_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane196"
								position={[2.07, -0.62, 0.72]}
								rotation={[-0.66, -0.45, -1.9]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane196_lambert6_0"
									geometry={gltf.nodes.pPlane196_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group name="pDisc1" position={[0, -0.06, 0]} scale={14.98}>
								<T.Mesh
									name="pDisc1_lambert3_0"
									geometry={gltf.nodes.pDisc1_lambert3_0.geometry}
									material={gltf.materials.lambert3}
								/>
							</T.Group>
							<T.Group name="pCylinder29" position={[0.03, 1.5, 0.1]}>
								<T.Mesh
									name="pCylinder29_lambert5_0"
									geometry={gltf.nodes.pCylinder29_lambert5_0.geometry}
									material={gltf.materials.lambert5}
								/>
							</T.Group>
							<T.Group name="pCube4" position={[2.81, 0.29, 1.73]}>
								<T.Mesh
									name="pCube4_lambert8_0"
									geometry={gltf.nodes.pCube4_lambert8_0.geometry}
									material={gltf.materials.lambert8}
								/>
							</T.Group>
							<T.Group name="polySurface90" position={[0, -0.04, 0]}>
								<T.Group name="polySurface91">
									<T.Mesh
										name="polySurface91_lambert6_0"
										geometry={gltf.nodes.polySurface91_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface92">
									<T.Mesh
										name="polySurface92_lambert6_0"
										geometry={gltf.nodes.polySurface92_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface93">
									<T.Mesh
										name="polySurface93_lambert6_0"
										geometry={gltf.nodes.polySurface93_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface94">
									<T.Mesh
										name="polySurface94_lambert6_0"
										geometry={gltf.nodes.polySurface94_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface95">
									<T.Mesh
										name="polySurface95_lambert6_0"
										geometry={gltf.nodes.polySurface95_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface96">
									<T.Mesh
										name="polySurface96_lambert6_0"
										geometry={gltf.nodes.polySurface96_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface97">
									<T.Mesh
										name="polySurface97_lambert6_0"
										geometry={gltf.nodes.polySurface97_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface98">
									<T.Mesh
										name="polySurface98_lambert6_0"
										geometry={gltf.nodes.polySurface98_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface99">
									<T.Mesh
										name="polySurface99_lambert6_0"
										geometry={gltf.nodes.polySurface99_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface100">
									<T.Mesh
										name="polySurface100_lambert6_0"
										geometry={gltf.nodes.polySurface100_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface101">
									<T.Mesh
										name="polySurface101_lambert6_0"
										geometry={gltf.nodes.polySurface101_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface102">
									<T.Mesh
										name="polySurface102_lambert6_0"
										geometry={gltf.nodes.polySurface102_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface103">
									<T.Mesh
										name="polySurface103_lambert6_0"
										geometry={gltf.nodes.polySurface103_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface104">
									<T.Mesh
										name="polySurface104_lambert6_0"
										geometry={gltf.nodes.polySurface104_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface105">
									<T.Mesh
										name="polySurface105_lambert6_0"
										geometry={gltf.nodes.polySurface105_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface106">
									<T.Mesh
										name="polySurface106_lambert6_0"
										geometry={gltf.nodes.polySurface106_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface107">
									<T.Mesh
										name="polySurface107_lambert6_0"
										geometry={gltf.nodes.polySurface107_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface108">
									<T.Mesh
										name="polySurface108_lambert6_0"
										geometry={gltf.nodes.polySurface108_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface109">
									<T.Mesh
										name="polySurface109_lambert6_0"
										geometry={gltf.nodes.polySurface109_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface110">
									<T.Mesh
										name="polySurface110_lambert6_0"
										geometry={gltf.nodes.polySurface110_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface111">
									<T.Mesh
										name="polySurface111_lambert6_0"
										geometry={gltf.nodes.polySurface111_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface112">
									<T.Mesh
										name="polySurface112_lambert6_0"
										geometry={gltf.nodes.polySurface112_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface113">
									<T.Mesh
										name="polySurface113_lambert6_0"
										geometry={gltf.nodes.polySurface113_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface114">
									<T.Mesh
										name="polySurface114_lambert6_0"
										geometry={gltf.nodes.polySurface114_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface115">
									<T.Mesh
										name="polySurface115_lambert6_0"
										geometry={gltf.nodes.polySurface115_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface116">
									<T.Mesh
										name="polySurface116_lambert6_0"
										geometry={gltf.nodes.polySurface116_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface117">
									<T.Mesh
										name="polySurface117_lambert6_0"
										geometry={gltf.nodes.polySurface117_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface118">
									<T.Mesh
										name="polySurface118_lambert6_0"
										geometry={gltf.nodes.polySurface118_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface119">
									<T.Mesh
										name="polySurface119_lambert6_0"
										geometry={gltf.nodes.polySurface119_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface120">
									<T.Mesh
										name="polySurface120_lambert6_0"
										geometry={gltf.nodes.polySurface120_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface121">
									<T.Mesh
										name="polySurface121_lambert6_0"
										geometry={gltf.nodes.polySurface121_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface122">
									<T.Mesh
										name="polySurface122_lambert6_0"
										geometry={gltf.nodes.polySurface122_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface123">
									<T.Mesh
										name="polySurface123_lambert6_0"
										geometry={gltf.nodes.polySurface123_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface124">
									<T.Mesh
										name="polySurface124_lambert6_0"
										geometry={gltf.nodes.polySurface124_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface125">
									<T.Mesh
										name="polySurface125_lambert6_0"
										geometry={gltf.nodes.polySurface125_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface126" position={[0, 0.59, 0]}>
									<T.Mesh
										name="polySurface126_lambert6_0"
										geometry={gltf.nodes.polySurface126_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface127">
									<T.Mesh
										name="polySurface127_lambert6_0"
										geometry={gltf.nodes.polySurface127_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface128">
									<T.Mesh
										name="polySurface128_lambert6_0"
										geometry={gltf.nodes.polySurface128_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface129">
									<T.Mesh
										name="polySurface129_lambert6_0"
										geometry={gltf.nodes.polySurface129_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface130">
									<T.Mesh
										name="polySurface130_lambert6_0"
										geometry={gltf.nodes.polySurface130_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface131">
									<T.Mesh
										name="polySurface131_lambert6_0"
										geometry={gltf.nodes.polySurface131_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface132">
									<T.Mesh
										name="polySurface132_lambert6_0"
										geometry={gltf.nodes.polySurface132_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface133">
									<T.Mesh
										name="polySurface133_lambert6_0"
										geometry={gltf.nodes.polySurface133_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface134">
									<T.Mesh
										name="polySurface134_lambert6_0"
										geometry={gltf.nodes.polySurface134_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface135">
									<T.Mesh
										name="polySurface135_lambert6_0"
										geometry={gltf.nodes.polySurface135_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface136">
									<T.Mesh
										name="polySurface136_lambert6_0"
										geometry={gltf.nodes.polySurface136_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface137">
									<T.Mesh
										name="polySurface137_lambert6_0"
										geometry={gltf.nodes.polySurface137_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface138">
									<T.Mesh
										name="polySurface138_lambert6_0"
										geometry={gltf.nodes.polySurface138_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface139">
									<T.Mesh
										name="polySurface139_lambert6_0"
										geometry={gltf.nodes.polySurface139_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface140">
									<T.Mesh
										name="polySurface140_lambert6_0"
										geometry={gltf.nodes.polySurface140_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface141">
									<T.Mesh
										name="polySurface141_lambert6_0"
										geometry={gltf.nodes.polySurface141_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface142">
									<T.Mesh
										name="polySurface142_lambert6_0"
										geometry={gltf.nodes.polySurface142_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface143">
									<T.Mesh
										name="polySurface143_lambert6_0"
										geometry={gltf.nodes.polySurface143_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface144">
									<T.Mesh
										name="polySurface144_lambert6_0"
										geometry={gltf.nodes.polySurface144_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface145">
									<T.Mesh
										name="polySurface145_lambert6_0"
										geometry={gltf.nodes.polySurface145_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface146">
									<T.Mesh
										name="polySurface146_lambert6_0"
										geometry={gltf.nodes.polySurface146_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface147">
									<T.Mesh
										name="polySurface147_lambert6_0"
										geometry={gltf.nodes.polySurface147_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface148">
									<T.Mesh
										name="polySurface148_lambert6_0"
										geometry={gltf.nodes.polySurface148_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface149">
									<T.Mesh
										name="polySurface149_lambert6_0"
										geometry={gltf.nodes.polySurface149_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface150">
									<T.Mesh
										name="polySurface150_lambert6_0"
										geometry={gltf.nodes.polySurface150_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface151">
									<T.Mesh
										name="polySurface151_lambert6_0"
										geometry={gltf.nodes.polySurface151_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface152">
									<T.Mesh
										name="polySurface152_lambert6_0"
										geometry={gltf.nodes.polySurface152_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface153">
									<T.Mesh
										name="polySurface153_lambert6_0"
										geometry={gltf.nodes.polySurface153_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface154">
									<T.Mesh
										name="polySurface154_lambert6_0"
										geometry={gltf.nodes.polySurface154_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface155">
									<T.Mesh
										name="polySurface155_lambert6_0"
										geometry={gltf.nodes.polySurface155_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface156">
									<T.Mesh
										name="polySurface156_lambert6_0"
										geometry={gltf.nodes.polySurface156_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface157">
									<T.Mesh
										name="polySurface157_lambert6_0"
										geometry={gltf.nodes.polySurface157_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface158">
									<T.Mesh
										name="polySurface158_lambert6_0"
										geometry={gltf.nodes.polySurface158_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface159">
									<T.Mesh
										name="polySurface159_lambert6_0"
										geometry={gltf.nodes.polySurface159_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface160">
									<T.Mesh
										name="polySurface160_lambert6_0"
										geometry={gltf.nodes.polySurface160_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface162">
									<T.Mesh
										name="polySurface162_lambert6_0"
										geometry={gltf.nodes.polySurface162_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface163">
									<T.Mesh
										name="polySurface163_lambert6_0"
										geometry={gltf.nodes.polySurface163_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface164">
									<T.Mesh
										name="polySurface164_lambert6_0"
										geometry={gltf.nodes.polySurface164_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface165">
									<T.Mesh
										name="polySurface165_lambert6_0"
										geometry={gltf.nodes.polySurface165_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group name="polySurface166">
									<T.Mesh
										name="polySurface166_lambert6_0"
										geometry={gltf.nodes.polySurface166_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface167"
									position={[-6.11, 0.54, -2.19]}
									rotation={[3.12, -0.85, 3.11]}
									scale={[1.69, 1, 1]}
								>
									<T.Mesh
										name="polySurface167_lambert6_0"
										geometry={gltf.nodes.polySurface167_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface173"
									position={[-9.43, 0.61, 0.84]}
									rotation={[0, -1.5, 0]}
									scale={0.21}
								>
									<T.Mesh
										name="polySurface173_lambert6_0"
										geometry={gltf.nodes.polySurface173_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface174"
									position={[3.3, 0.05, -8.31]}
									rotation={[-2.95, 0.02, -3.12]}
									scale={[0.3, 0.21, 0.21]}
								>
									<T.Mesh
										name="polySurface174_lambert6_0"
										geometry={gltf.nodes.polySurface174_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface175"
									position={[-2.05, 0.1, -6.78]}
									rotation={[Math.PI, -0.93, 3.13]}
									scale={0.21}
								>
									<T.Mesh
										name="polySurface175_lambert6_0"
										geometry={gltf.nodes.polySurface175_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface176"
									position={[0.57, 0.07, -5.02]}
									rotation={[Math.PI, -0.93, 3.13]}
									scale={0.21}
								>
									<T.Mesh
										name="polySurface176_lambert6_0"
										geometry={gltf.nodes.polySurface176_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface177"
									position={[3.24, 0.58, 9.17]}
									rotation={[0, -1.5, 0.2]}
									scale={0.21}
								>
									<T.Mesh
										name="polySurface177_lambert6_0"
										geometry={gltf.nodes.polySurface177_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface178"
									position={[9.04, 0.11, 0.84]}
									rotation={[Math.PI, 1.27, -3.07]}
									scale={[0.48, 0.26, 0.32]}
								>
									<T.Mesh
										name="polySurface178_lambert6_0"
										geometry={gltf.nodes.polySurface178_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface179"
									position={[-4.02, 0.43, -8.31]}
									rotation={[-2.95, 0.02, -2.91]}
									scale={[0.3, 0.21, 0.21]}
								>
									<T.Mesh
										name="polySurface179_lambert6_0"
										geometry={gltf.nodes.polySurface179_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface180"
									position={[-6.92, 0.19, 2.78]}
									rotation={[-2.95, 0.02, -2.93]}
									scale={[0.3, 0.21, 0.21]}
								>
									<T.Mesh
										name="polySurface180_lambert6_0"
										geometry={gltf.nodes.polySurface180_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface181"
									position={[-5.59, 0.6, 6.92]}
									rotation={[-2.95, 0.02, -2.87]}
									scale={[0.3, 0.21, 0.21]}
								>
									<T.Mesh
										name="polySurface181_lambert6_0"
										geometry={gltf.nodes.polySurface181_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
								<T.Group
									name="polySurface182"
									position={[-2.11, 0.05, 6.96]}
									rotation={[0, -1.5, 0.04]}
									scale={0.21}
								>
									<T.Mesh
										name="polySurface182_lambert6_0"
										geometry={gltf.nodes.polySurface182_lambert6_0.geometry}
										material={gltf.materials.lambert6}
									/>
								</T.Group>
							</T.Group>
							<T.Group
								name="pPlane1"
								position={[-4.68, -0.02, -3.49]}
								rotation={[-0.03, 0.52, -1.46]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane1_lambert6_0"
									geometry={gltf.nodes.pPlane1_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane2"
								position={[-4.37, 0.07, 1.16]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane2_lambert6_0"
									geometry={gltf.nodes.pPlane2_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane3"
								position={[-4.07, -0.01, -1.74]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane3_lambert6_0"
									geometry={gltf.nodes.pPlane3_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane4"
								position={[-4.8, 0.07, -0.12]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane4_lambert6_0"
									geometry={gltf.nodes.pPlane4_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane5"
								position={[-6, 0.07, 0]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane5_lambert6_0"
									geometry={gltf.nodes.pPlane5_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane6"
								position={[-4.94, 0.07, 2.25]}
								rotation={[-0.03, 0.52, -1.46]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane6_lambert6_0"
									geometry={gltf.nodes.pPlane6_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane7"
								position={[-5.51, -0.02, -1.6]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane7_lambert6_0"
									geometry={gltf.nodes.pPlane7_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane8"
								position={[-5.81, 0.07, 0.16]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane8_lambert6_0"
									geometry={gltf.nodes.pPlane8_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane9"
								position={[-5.81, 0.07, 0.48]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane9_lambert6_0"
									geometry={gltf.nodes.pPlane9_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane10"
								position={[-3.25, -0.03, 6.03]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane10_lambert6_0"
									geometry={gltf.nodes.pPlane10_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane11"
								position={[-3.82, 0.21, 7.12]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane11_lambert6_0"
									geometry={gltf.nodes.pPlane11_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane12"
								position={[-4.38, -0.04, 4.75]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane12_lambert6_0"
									geometry={gltf.nodes.pPlane12_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane13"
								position={[-3.65, 0.04, 3.13]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane13_lambert6_0"
									geometry={gltf.nodes.pPlane13_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane14"
								position={[-5.09, -0.03, 3.27]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane14_lambert6_0"
									geometry={gltf.nodes.pPlane14_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane15"
								position={[-4.26, 0.04, 1.38]}
								rotation={[-0.05, -0.22, -1.6]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane15_lambert6_0"
									geometry={gltf.nodes.pPlane15_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane16"
								position={[-4.69, 0.05, 5.03]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane16_lambert6_0"
									geometry={gltf.nodes.pPlane16_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane17"
								position={[-4.69, 0.1, 5.35]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane17_lambert6_0"
									geometry={gltf.nodes.pPlane17_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane18"
								position={[-4.88, 0.04, 4.87]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane18_lambert6_0"
									geometry={gltf.nodes.pPlane18_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane19"
								position={[-2.37, -0.04, 6.54]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane19_lambert6_0"
									geometry={gltf.nodes.pPlane19_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane20"
								position={[-2.17, -0.04, 7.02]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane20_lambert6_0"
									geometry={gltf.nodes.pPlane20_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane21"
								position={[-2.17, -0.03, 6.69]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane21_lambert6_0"
									geometry={gltf.nodes.pPlane21_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane22"
								position={[-1.87, -0.02, 6.42]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane22_lambert6_0"
									geometry={gltf.nodes.pPlane22_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane23"
								position={[-0.73, 0.01, 7.7]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane23_lambert6_0"
									geometry={gltf.nodes.pPlane23_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane24"
								position={[-2.62, -0.03, 8.51]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane24_lambert6_0"
									geometry={gltf.nodes.pPlane24_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane25"
								position={[-0.77, 0.22, 9.2]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane25_lambert6_0"
									geometry={gltf.nodes.pPlane25_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane26"
								position={[-2.21, -0.02, 8.19]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane26_lambert6_0"
									geometry={gltf.nodes.pPlane26_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane27"
								position={[-2.41, -0.03, 8.9]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane27_lambert6_0"
									geometry={gltf.nodes.pPlane27_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane28"
								position={[-1.91, -0.01, 7.91]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane28_lambert6_0"
									geometry={gltf.nodes.pPlane28_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane29"
								position={[0.17, 0.55, 10.48]}
								rotation={[-0.03, 0.6, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane29_lambert6_0"
									geometry={gltf.nodes.pPlane29_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane30"
								position={[1.34, 0.61, 10.27]}
								rotation={[-0.03, 0.6, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane30_lambert6_0"
									geometry={gltf.nodes.pPlane30_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane31"
								position={[0.21, 0.28, 8.99]}
								rotation={[-0.03, 0.6, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane31_lambert6_0"
									geometry={gltf.nodes.pPlane31_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane32"
								position={[-4.62, 0.44, 7.42]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane32_lambert6_0"
									geometry={gltf.nodes.pPlane32_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane33"
								position={[-5.51, 0.58, 6.63]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane33_lambert6_0"
									geometry={gltf.nodes.pPlane33_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane34"
								position={[-4.49, 0.42, 6.67]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane34_lambert6_0"
									geometry={gltf.nodes.pPlane34_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane35"
								position={[-4.62, 0.43, 8.95]}
								rotation={[0.32, 0.48, -1.78]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane35_lambert6_0"
									geometry={gltf.nodes.pPlane35_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane36"
								position={[-4.49, 0.4, 8.19]}
								rotation={[0.32, 0.48, -1.78]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane36_lambert6_0"
									geometry={gltf.nodes.pPlane36_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane37"
								position={[-5.51, 0.71, 8.16]}
								rotation={[0.32, 0.48, -1.78]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane37_lambert6_0"
									geometry={gltf.nodes.pPlane37_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane38"
								position={[-6.02, 0.74, 8.95]}
								rotation={[0.38, 0.47, -1.81]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane38_lambert6_0"
									geometry={gltf.nodes.pPlane38_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane39"
								position={[-5.88, 0.83, 8.19]}
								rotation={[0.32, 0.48, -1.78]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane39_lambert6_0"
									geometry={gltf.nodes.pPlane39_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane40"
								position={[-5.88, 0.77, 7.33]}
								rotation={[-0.1, 0.52, -1.57]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane40_lambert6_0"
									geometry={gltf.nodes.pPlane40_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane41"
								position={[-5.23, 0.63, 7.29]}
								rotation={[-0.1, 0.52, -1.57]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane41_lambert6_0"
									geometry={gltf.nodes.pPlane41_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane42"
								position={[-8.44, 0.48, 4.52]}
								rotation={[-0.1, 0.52, -1.57]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane42_lambert6_0"
									geometry={gltf.nodes.pPlane42_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane43"
								position={[-9.09, 0.64, 4.56]}
								rotation={[-0.1, 0.52, -1.57]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane43_lambert6_0"
									geometry={gltf.nodes.pPlane43_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane44"
								position={[-8.72, 0.66, 5.39]}
								rotation={[0.03, 0.52, -1.64]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane44_lambert6_0"
									geometry={gltf.nodes.pPlane44_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane45"
								position={[-9.09, 0.71, 5.42]}
								rotation={[0.12, 0.51, -1.68]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane45_lambert6_0"
									geometry={gltf.nodes.pPlane45_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane46"
								position={[-7.92, 0.79, 6.1]}
								rotation={[-0.1, 0.52, -1.57]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane46_lambert6_0"
									geometry={gltf.nodes.pPlane46_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane47"
								position={[-7.92, 0.97, 6.97]}
								rotation={[0.12, 0.51, -1.68]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane47_lambert6_0"
									geometry={gltf.nodes.pPlane47_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane48"
								position={[-7.55, 0.93, 6.93]}
								rotation={[-0.18, 0.52, -1.53]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane48_lambert6_0"
									geometry={gltf.nodes.pPlane48_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane49"
								position={[-7.27, 0.7, 6.07]}
								rotation={[-0.1, 0.52, -1.57]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane49_lambert6_0"
									geometry={gltf.nodes.pPlane49_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane50"
								position={[-5.95, 0.07, 4.41]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane50_lambert6_0"
									geometry={gltf.nodes.pPlane50_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane51"
								position={[-6.14, -0.01, 3.93]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane51_lambert6_0"
									geometry={gltf.nodes.pPlane51_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane52"
								position={[-4.29, 0.05, 2.59]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane52_lambert6_0"
									geometry={gltf.nodes.pPlane52_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane53"
								position={[-6.36, -0.01, 2.33]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane53_lambert6_0"
									geometry={gltf.nodes.pPlane53_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane54"
								position={[-8.5, 0.46, 1.16]}
								rotation={[-0.03, 0.52, -1.46]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane54_lambert6_0"
									geometry={gltf.nodes.pPlane54_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane55"
								position={[-8.43, 0.46, 2.59]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane55_lambert6_0"
									geometry={gltf.nodes.pPlane55_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane56"
								position={[-7.79, 0.25, 3.13]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane56_lambert6_0"
									geometry={gltf.nodes.pPlane56_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane57"
								position={[-9.23, 0.59, 3.27]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane57_lambert6_0"
									geometry={gltf.nodes.pPlane57_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane58"
								position={[-9.08, 0.57, 2.25]}
								rotation={[-0.03, 0.52, -1.46]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane58_lambert6_0"
									geometry={gltf.nodes.pPlane58_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane59"
								position={[-9.94, 0.7, 0.48]}
								rotation={[-0.03, 0.52, -1.46]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane59_lambert6_0"
									geometry={gltf.nodes.pPlane59_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane60"
								position={[-6.81, 0, 3.13]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane60_lambert6_0"
									geometry={gltf.nodes.pPlane60_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane61"
								position={[-6.72, 0.18, 4.52]}
								rotation={[-0.1, 0.52, -1.57]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane61_lambert6_0"
									geometry={gltf.nodes.pPlane61_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane62"
								position={[-7.18, 0.16, 4]}
								rotation={[-0.1, 0.52, -1.57]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane62_lambert6_0"
									geometry={gltf.nodes.pPlane62_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane63"
								position={[-1.63, 0.04, -5.71]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane63_lambert6_0"
									geometry={gltf.nodes.pPlane63_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane64"
								position={[-0.92, 0.04, -4.24]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane64_lambert6_0"
									geometry={gltf.nodes.pPlane64_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane65"
								position={[-2.49, 0.04, -4.58]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane65_lambert6_0"
									geometry={gltf.nodes.pPlane65_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane66"
								position={[-2.68, 0.06, -5.06]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane66_lambert6_0"
									geometry={gltf.nodes.pPlane66_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane67"
								position={[-1.42, 0.02, -4.12]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane67_lambert6_0"
									geometry={gltf.nodes.pPlane67_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane68"
								position={[-0.19, 0.04, -5.85]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane68_lambert6_0"
									geometry={gltf.nodes.pPlane68_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane69"
								position={[-0.83, 0.05, -6.4]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane69_lambert6_0"
									geometry={gltf.nodes.pPlane69_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane70"
								position={[-1.48, 0.07, -6.73]}
								rotation={[0.18, -1, -1.39]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane70_lambert6_0"
									geometry={gltf.nodes.pPlane70_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane71"
								position={[-0.8, 0.04, -7.6]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane71_lambert6_0"
									geometry={gltf.nodes.pPlane71_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane72"
								position={[-0.9, 0.07, -7.82]}
								rotation={[0.18, -1, -1.39]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane72_lambert6_0"
									geometry={gltf.nodes.pPlane72_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane73"
								position={[1.18, 0.04, -5.71]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane73_lambert6_0"
									geometry={gltf.nodes.pPlane73_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane74"
								position={[1.89, 0.04, -4.24]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane74_lambert6_0"
									geometry={gltf.nodes.pPlane74_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane75"
								position={[0.32, 0.04, -4.58]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane75_lambert6_0"
									geometry={gltf.nodes.pPlane75_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane76"
								position={[0.12, 0.06, -5.06]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane76_lambert6_0"
									geometry={gltf.nodes.pPlane76_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane77"
								position={[1.39, 0.05, -4.12]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane77_lambert6_0"
									geometry={gltf.nodes.pPlane77_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane78"
								position={[2.62, 0.04, -5.85]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane78_lambert6_0"
									geometry={gltf.nodes.pPlane78_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane79"
								position={[1.98, 0.05, -6.4]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane79_lambert6_0"
									geometry={gltf.nodes.pPlane79_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane80"
								position={[1.33, 0.07, -6.73]}
								rotation={[0.18, -1, -1.39]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane80_lambert6_0"
									geometry={gltf.nodes.pPlane80_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane81"
								position={[2.01, 0.04, -7.6]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane81_lambert6_0"
									geometry={gltf.nodes.pPlane81_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane82"
								position={[1.9, 0.07, -7.82]}
								rotation={[0.18, -1, -1.39]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane82_lambert6_0"
									geometry={gltf.nodes.pPlane82_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane83"
								position={[4.33, 0.05, -4.43]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane83_lambert6_0"
									geometry={gltf.nodes.pPlane83_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane84"
								position={[5.41, -0.02, -3.97]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane84_lambert6_0"
									geometry={gltf.nodes.pPlane84_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane85"
								position={[4.14, 0.07, -4.91]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane85_lambert6_0"
									geometry={gltf.nodes.pPlane85_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane86"
								position={[3.83, 0.09, -5.71]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane86_lambert6_0"
									geometry={gltf.nodes.pPlane86_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane87"
								position={[5.2, 0.22, -5.57]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane87_lambert6_0"
									geometry={gltf.nodes.pPlane87_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane88"
								position={[5.91, 0.04, -4.09]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane88_lambert6_0"
									geometry={gltf.nodes.pPlane88_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane89"
								position={[6.64, 0.36, -5.71]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane89_lambert6_0"
									geometry={gltf.nodes.pPlane89_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane90"
								position={[6, 0.37, -6.26]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane90_lambert6_0"
									geometry={gltf.nodes.pPlane90_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane91"
								position={[5.35, 0.39, -6.59]}
								rotation={[0.18, -1, -1.39]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane91_lambert6_0"
									geometry={gltf.nodes.pPlane91_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane92"
								position={[-0.22, 0.61, -10.85]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane92_lambert6_0"
									geometry={gltf.nodes.pPlane92_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane93"
								position={[0.1, 0.49, -10.06]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane93_lambert6_0"
									geometry={gltf.nodes.pPlane93_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane94"
								position={[0.32, 0.1, -9.57]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane94_lambert6_0"
									geometry={gltf.nodes.pPlane94_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane95"
								position={[-0.92, 0.09, -9.23]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane95_lambert6_0"
									geometry={gltf.nodes.pPlane95_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane96"
								position={[-0.83, 0.7, -11.4]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane96_lambert6_0"
									geometry={gltf.nodes.pPlane96_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane97"
								position={[-1.48, 0.12, -11.73]}
								rotation={[0.18, -1, -1.39]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane97_lambert6_0"
									geometry={gltf.nodes.pPlane97_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane98"
								position={[1.18, 0.45, -10.71]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane98_lambert6_0"
									geometry={gltf.nodes.pPlane98_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane99"
								position={[1.33, 0.44, -11.73]}
								rotation={[-0.61, -0.93, -2.05]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane99_lambert6_0"
									geometry={gltf.nodes.pPlane99_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane100"
								position={[1.39, 0.1, -9.12]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane100_lambert6_0"
									geometry={gltf.nodes.pPlane100_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane101"
								position={[1.89, 0.09, -9.23]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane101_lambert6_0"
									geometry={gltf.nodes.pPlane101_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane102"
								position={[1.98, 0.34, -11.4]}
								rotation={[-0.79, -0.86, -2.2]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane102_lambert6_0"
									geometry={gltf.nodes.pPlane102_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane103"
								position={[-4.48, 0.5, -7.89]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane103_lambert6_0"
									geometry={gltf.nodes.pPlane103_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane104"
								position={[-3.08, 0.31, -8.31]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane104_lambert6_0"
									geometry={gltf.nodes.pPlane104_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane105"
								position={[-4.16, 0.37, -7.09]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane105_lambert6_0"
									geometry={gltf.nodes.pPlane105_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane106"
								position={[-2.28, 0.33, -8.99]}
								rotation={[-0.79, -0.86, -2.2]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane106_lambert6_0"
									geometry={gltf.nodes.pPlane106_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane107"
								position={[-2.93, 0.4, -9.33]}
								rotation={[-0.61, -0.93, -2.05]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane107_lambert6_0"
									geometry={gltf.nodes.pPlane107_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane108"
								position={[-5.09, 0.61, -8.43]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane108_lambert6_0"
									geometry={gltf.nodes.pPlane108_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane109"
								position={[-2.37, 0.09, -6.83]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane109_lambert6_0"
									geometry={gltf.nodes.pPlane109_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane110"
								position={[-2.87, 0.1, -6.71]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane110_lambert6_0"
									geometry={gltf.nodes.pPlane110_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane111"
								position={[-2.36, 0.06, -5.42]}
								rotation={[0.18, -1, -1.39]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane111_lambert6_0"
									geometry={gltf.nodes.pPlane111_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane112"
								position={[-2.25, 0.03, -5.2]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane112_lambert6_0"
									geometry={gltf.nodes.pPlane112_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane113"
								position={[-4.43, -0.02, -3.02]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane113_lambert6_0"
									geometry={gltf.nodes.pPlane113_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane114"
								position={[-5.14, 0.07, -4.5]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane114_lambert6_0"
									geometry={gltf.nodes.pPlane114_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane115"
								position={[-3.71, -0.02, -4.64]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane115_lambert6_0"
									geometry={gltf.nodes.pPlane115_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane116"
								position={[-5.44, 0.07, -2.74]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane116_lambert6_0"
									geometry={gltf.nodes.pPlane116_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane117"
								position={[-5.63, 0.07, -2.9]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane117_lambert6_0"
									geometry={gltf.nodes.pPlane117_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane118"
								position={[-5.44, -0.03, -2.42]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane118_lambert6_0"
									geometry={gltf.nodes.pPlane118_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane119"
								position={[-4, -0.01, -1.74]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane119_lambert6_0"
									geometry={gltf.nodes.pPlane119_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane120"
								position={[-3.9, -0.01, -1.52]}
								rotation={[-0.06, -0.37, -1.6]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane120_lambert6_0"
									geometry={gltf.nodes.pPlane120_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane121"
								position={[-8.43, 0.46, -3.02]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane121_lambert6_0"
									geometry={gltf.nodes.pPlane121_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane122"
								position={[-9.14, 0.1, -4.5]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane122_lambert6_0"
									geometry={gltf.nodes.pPlane122_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane123"
								position={[-7.7, 0.04, -4.64]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane123_lambert6_0"
									geometry={gltf.nodes.pPlane123_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane124"
								position={[-9.44, 0.46, -2.74]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane124_lambert6_0"
									geometry={gltf.nodes.pPlane124_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane125"
								position={[-9.63, 0.46, -2.9]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane125_lambert6_0"
									geometry={gltf.nodes.pPlane125_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane126"
								position={[-9.44, 0.46, -2.42]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane126_lambert6_0"
									geometry={gltf.nodes.pPlane126_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane127"
								position={[-8, 0.23, -1.74]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane127_lambert6_0"
									geometry={gltf.nodes.pPlane127_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane128"
								position={[-7.89, 0.2, -1.52]}
								rotation={[-0.06, -0.37, -1.6]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane128_lambert6_0"
									geometry={gltf.nodes.pPlane128_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane129"
								position={[-7.4, 0.5, -6.81]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane129_lambert6_0"
									geometry={gltf.nodes.pPlane129_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane130"
								position={[-6.78, 0.43, -6.26]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane130_lambert6_0"
									geometry={gltf.nodes.pPlane130_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane131"
								position={[-6.47, 0.26, -5.47]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane131_lambert6_0"
									geometry={gltf.nodes.pPlane131_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane132"
								position={[1.58, 0.28, 7.9]}
								rotation={[-0.03, 0.6, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane132_lambert6_0"
									geometry={gltf.nodes.pPlane132_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane133"
								position={[0.59, 0.22, 8.11]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane133_lambert6_0"
									geometry={gltf.nodes.pPlane133_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane134"
								position={[-1.04, -0.01, 7.81]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane134_lambert6_0"
									geometry={gltf.nodes.pPlane134_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane135"
								position={[-1.3, 0.03, 8.94]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane135_lambert6_0"
									geometry={gltf.nodes.pPlane135_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane136"
								position={[-0.89, 0.04, 8.62]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane136_lambert6_0"
									geometry={gltf.nodes.pPlane136_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane137"
								position={[-0.54, -0.01, 6.82]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane137_lambert6_0"
									geometry={gltf.nodes.pPlane137_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane138"
								position={[0.63, 0.07, 6.61]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane138_lambert6_0"
									geometry={gltf.nodes.pPlane138_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane139"
								position={[1.93, 0.52, 10.27]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane139_lambert6_0"
									geometry={gltf.nodes.pPlane139_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane140"
								position={[0.61, 0.37, 9.86]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane140_lambert6_0"
									geometry={gltf.nodes.pPlane140_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane141"
								position={[0.8, 0.27, 8.98]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane141_lambert6_0"
									geometry={gltf.nodes.pPlane141_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane142"
								position={[-5.27, -0.03, 1.16]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane142_lambert6_0"
									geometry={gltf.nodes.pPlane142_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane143"
								position={[-5.2, -0.04, 2.59]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane143_lambert6_0"
									geometry={gltf.nodes.pPlane143_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane144"
								position={[-7.05, -0.1, 3.93]}
								rotation={[-0.03, 0.52, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane144_lambert6_0"
									geometry={gltf.nodes.pPlane144_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane145"
								position={[-2.39, -0.02, 5.01]}
								rotation={[0.07, 1.31, -1.69]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane145_lambert6_0"
									geometry={gltf.nodes.pPlane145_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane146"
								position={[-3.12, -0.04, 5.65]}
								rotation={[0.07, 1.31, -1.69]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane146_lambert6_0"
									geometry={gltf.nodes.pPlane146_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane147"
								position={[-3.35, -0.02, 5.01]}
								rotation={[-0.02, 0.76, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane147_lambert6_0"
									geometry={gltf.nodes.pPlane147_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane148"
								position={[-3.02, -0.02, 4.01]}
								rotation={[-0.02, 0.76, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane148_lambert6_0"
									geometry={gltf.nodes.pPlane148_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane149"
								position={[-3.02, -0.02, 4.49]}
								rotation={[-0.02, 0.76, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane149_lambert6_0"
									geometry={gltf.nodes.pPlane149_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane150"
								position={[-3.95, -0.02, 4.15]}
								rotation={[-0.03, 0.49, -1.61]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane150_lambert6_0"
									geometry={gltf.nodes.pPlane150_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane151"
								position={[-5.08, -0.02, -1.18]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane151_lambert6_0"
									geometry={gltf.nodes.pPlane151_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane152"
								position={[-3.64, -0.02, -0.17]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane152_lambert6_0"
									geometry={gltf.nodes.pPlane152_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane153"
								position={[-4.21, -0.02, 0.92]}
								rotation={[-0.03, 0.52, -1.46]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane153_lambert6_0"
									geometry={gltf.nodes.pPlane153_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane154"
								position={[-4.07, -0.02, -1.45]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane154_lambert6_0"
									geometry={gltf.nodes.pPlane154_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane155"
								position={[-4.22, -0.02, -0.17]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane155_lambert6_0"
									geometry={gltf.nodes.pPlane155_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane156"
								position={[-4.22, -0.02, -0.89]}
								rotation={[0.05, -0.21, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane156_lambert6_0"
									geometry={gltf.nodes.pPlane156_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane157"
								position={[-3.81, -0.01, -3.59]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane157_lambert6_0"
									geometry={gltf.nodes.pPlane157_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane158"
								position={[-2.73, -0.03, -3.13]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane158_lambert6_0"
									geometry={gltf.nodes.pPlane158_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane159"
								position={[-2.23, -0.01, -3.25]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane159_lambert6_0"
									geometry={gltf.nodes.pPlane159_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane160"
								position={[-3.57, -0.06, -4.21]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane160_lambert6_0"
									geometry={gltf.nodes.pPlane160_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane161"
								position={[-4, -0.02, -4.07]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane161_lambert6_0"
									geometry={gltf.nodes.pPlane161_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane162"
								position={[-5.32, 0.07, -0.75]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane162_lambert6_0"
									geometry={gltf.nodes.pPlane162_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane163"
								position={[-3.71, -0.02, -3.66]}
								rotation={[0.06, -0.36, -1.47]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane163_lambert6_0"
									geometry={gltf.nodes.pPlane163_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane164"
								position={[-2.23, -0.01, -2.27]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane164_lambert6_0"
									geometry={gltf.nodes.pPlane164_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane165"
								position={[-2.73, -0.03, -2.16]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane165_lambert6_0"
									geometry={gltf.nodes.pPlane165_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane166"
								position={[-3.81, -0.01, -2.61]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane166_lambert6_0"
									geometry={gltf.nodes.pPlane166_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane167"
								position={[-4, -0.02, -3.1]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane167_lambert6_0"
									geometry={gltf.nodes.pPlane167_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane168"
								position={[7.25, 0.05, -2.87]}
								rotation={[0.18, -1, -1.39]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane168_lambert6_0"
									geometry={gltf.nodes.pPlane168_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane169"
								position={[7.36, 0.02, -2.65]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane169_lambert6_0"
									geometry={gltf.nodes.pPlane169_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane170"
								position={[7.33, 0.02, -1.45]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane170_lambert6_0"
									geometry={gltf.nodes.pPlane170_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane171"
								position={[5.88, -0.05, -4.04]}
								rotation={[-0.79, -0.86, -2.2]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane171_lambert6_0"
									geometry={gltf.nodes.pPlane171_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane172"
								position={[6.68, 0.27, -6.78]}
								rotation={[0.18, -1, -1.39]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane172_lambert6_0"
									geometry={gltf.nodes.pPlane172_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane173"
								position={[7.33, 0.5, -6.45]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane173_lambert6_0"
									geometry={gltf.nodes.pPlane173_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane174"
								position={[7.24, 0.24, -4.28]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane174_lambert6_0"
									geometry={gltf.nodes.pPlane174_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane175"
								position={[7.94, 0.46, -5.9]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane175_lambert6_0"
									geometry={gltf.nodes.pPlane175_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane176"
								position={[8.48, 0.24, -4.62]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane176_lambert6_0"
									geometry={gltf.nodes.pPlane176_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane177"
								position={[8.26, 0.34, -5.1]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane177_lambert6_0"
									geometry={gltf.nodes.pPlane177_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane178"
								position={[10.14, 0.32, -3.07]}
								rotation={[-0.79, -0.86, -2.2]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane178_lambert6_0"
									geometry={gltf.nodes.pPlane178_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane179"
								position={[10.05, 0.24, -4.28]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane179_lambert6_0"
									geometry={gltf.nodes.pPlane179_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane180"
								position={[9.55, 0.25, -4.16]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane180_lambert6_0"
									geometry={gltf.nodes.pPlane180_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane181"
								position={[9.49, 0.3, -3.4]}
								rotation={[-0.61, -0.93, -2.05]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane181_lambert6_0"
									geometry={gltf.nodes.pPlane181_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlane182"
								position={[9.34, 0.59, -5.76]}
								rotation={[-0.1, -1.01, -1.63]}
								scale={[0.16, 0.2, 0.1]}
							>
								<T.Mesh
									name="pPlane182_lambert6_0"
									geometry={gltf.nodes.pPlane182_lambert6_0.geometry}
									material={gltf.materials.lambert6}
								/>
							</T.Group>
							<T.Group
								name="pPlatonic7"
								position={[-6.51, -0.07, 3.13]}
								rotation={[-0.08, 1.31, 0.38]}
								scale={[0.26, 0.15, 0.24]}
							>
								<T.Mesh
									name="pPlatonic7_lambert7_0"
									geometry={gltf.nodes.pPlatonic7_lambert7_0.geometry}
									material={gltf.materials.lambert7}
								/>
							</T.Group>
							<T.Group name="pCube6" position={[-0.24, 0.31, 0.57]}>
								<T.Mesh
									name="pCube6_lambert7_0"
									geometry={gltf.nodes.pCube6_lambert7_0.geometry}
									material={gltf.materials.lambert7}
								/>
							</T.Group>
							<T.Group name="fire3polySurface161">
								<T.Group name="fire3polySurface162">
									<T.Mesh
										name="fire3polySurface162_fire3lambert2_0"
										geometry={gltf.nodes.fire3polySurface162_fire3lambert2_0.geometry}
										material={gltf.materials.fire3lambert2}
									/>
								</T.Group>
								<T.Group
									name="fire3polySurface163"
									position={[4.49, 0.12, 0.21]}
									rotation={[0.31, 0.55, 2.27]}
								>
									<T.Mesh
										name="fire3polySurface163_fire3lambert2_0"
										geometry={gltf.nodes.fire3polySurface163_fire3lambert2_0.geometry}
										material={gltf.materials.fire3lambert2}
									/>
								</T.Group>
								<T.Group
									name="polySurface163_1"
									position={[3.31, -0.02, 0.89]}
									rotation={[0.31, 0.55, 2.27]}
									scale={0.23}
								>
									<T.Mesh
										name="polySurface163_fire3lambert2_0"
										geometry={gltf.nodes.polySurface163_fire3lambert2_0.geometry}
										material={gltf.materials.fire3lambert2}
									/>
								</T.Group>
								<T.Group
									name="polySurface183"
									position={[3.12, 0.01, 0.77]}
									rotation={[0.4, -0.03, 2.56]}
									scale={0.23}
								>
									<T.Mesh
										name="polySurface183_fire3lambert2_0"
										geometry={gltf.nodes.polySurface183_fire3lambert2_0.geometry}
										material={gltf.materials.fire3lambert2}
									/>
								</T.Group>
								<T.Group
									name="polySurface184"
									position={[3.52, 0.01, 0.71]}
									rotation={[0.18, 0.95, 2.86]}
									scale={0.23}
								>
									<T.Mesh
										name="polySurface184_fire3lambert2_0"
										geometry={gltf.nodes.polySurface184_fire3lambert2_0.geometry}
										material={gltf.materials.fire3lambert2}
									/>
								</T.Group>
								<T.Group
									name="polySurface185"
									position={[3.52, 0.13, 0.71]}
									rotation={[1.71, 1.09, 1.37]}
									scale={0.23}
								>
									<T.Mesh
										name="polySurface185_fire3lambert2_0"
										geometry={gltf.nodes.polySurface185_fire3lambert2_0.geometry}
										material={gltf.materials.fire3lambert2}
									/>
								</T.Group>
							</T.Group>
							<T.Group name="fire6Group20972" position={[2.82, 0.41, 1.73]} scale={0.29}>
								<T.Mesh
									name="0"
									geometry={gltf.nodes['0'].geometry}
									material={gltf.materials.lambert9}
									morphTargetDictionary={gltf.nodes['0'].morphTargetDictionary}
									morphTargetInfluences={gltf.nodes['0'].morphTargetInfluences}
								/>
							</T.Group>
						</T.Group>
					</T.Group>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
